[connections.snowflake]
account = "COLLIBRA_PARTNER"
user = "TECHNICAL_PARTNERSHIPS"
private_key_file = "technical_partnerships.p8"
role = "TECHNICAL_PARTNERSHIPS"
warehouse = "TECHNICAL_PARTNERSHIPS"
database = "WIZ_IO_DB"
schema = "WIZ_IO_SCHEMA"